# Generated by Django 3.2.6 on 2021-08-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(verbose_name='زمان'),
        ),
    ]
