# Generated by Django 3.2.6 on 2021-08-22 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_note_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 14, 19, 25, 535303, tzinfo=utc), verbose_name='زمان'),
        ),
    ]
