# Generated by Django 3.2.6 on 2021-08-22 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_note_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان'),
        ),
    ]
